export const BATTLE_STATES = {
    INTRO: "INTRO",
    PRE_BATTLE_INFO: "PRE_BATTLE_INFO",
    BRING_OUT_MONSTER: "BRING_OUT_MONSTER",
    PLAYER_INPUT: "PLAYER_INPUT",
    ENEMY_INPUT: "ENEMY_INPUT",
    BATTLE: "BATTLE",
    POST_ATTACK_CHECK: "POST_ATTACK_CHECK",
    FINISHED: "FINISHED",
    FLEE_ATTEMPT: "FLEE_ATTEMPT",
    GAIN_EXPERIENCE: "GAIN_EXPERIENCE",
} as const;

export type BattleState = (typeof BATTLE_STATES)[keyof typeof BATTLE_STATES];
