export enum SCENE_KEYS {
    PRELOAD_SCENE = "PRELOAD_SCENE",
    WORLD_SCENE = "WORLD_SCENE",
    BATTLE_SCENE = "BATTLE_SCENE",
    TITLE_SCENE = 'TITLE_SCENE',
    MONSTER_PARTY_SCENE = 'MONSTER_PARTY_SCENE',
}
